In [105]:
import requests
import datetime as dt
import pandas as pd
import numpy as np
import os
import json

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')

In [106]:
BASEURL = "https://api.nomics.com/v1"

def get_quote_rates(APIKEY):
    if not os.path.exists("../nomics_rates"):
        os.mkdir("../nomics_rates")
        
    get_url = BASEURL + "/exchange-rates"
    
    _params = {
        "key": APIKEY
    }

    response = requests.get(get_url, _params)
    response_json = response.json()
    df = pd.DataFrame(response_json)
    df.loc[:, 'timestamp'] = pd.to_datetime(df['timestamp'])
    
    return df

def exists_in_currencies(APIKEY, target):
    if not os.path.exists("../nomics_rates"):
        os.mkdir("../nomics_rates")
        
    get_url = BASEURL + "/currencies"
    
    _params = {
        "key": APIKEY
    }

    response = requests.get(get_url, _params)
    response_json = response.json()
    df = pd.DataFrame(response_json)
    
    exists = target in df
    
    return exists

def load_historical_price(APIKEY, start_time, end_time):
    
    get_url = BASEURL + "/currencies/interval"
        
    _params = {
        "key": APIKEY,
        "start": start_time,
        "end": end_time,
    }

    response = requests.get(get_url, params=_params)
    response_json = response.json()
    df = pd.DataFrame(response_json)
    return df

In [107]:

apikey = json.loads(open("../nomics_apikey.json").read())["APIKEY"]
# list_quote_rates = get_quote_rates(apikey)
# does_DAI_exist = exists_in_currencies(apikey, "DAI")

fmt_dt = lambda d: "{:%Y-%m-%dT%H:%M:%SZ}".format(d)
start_dt = dt.datetime(2018, 1, 1)
end_dt = dt.datetime(2018, 12, 31)
hist_prices = load_historical_price(apikey, fmt_dt(start_dt), fmt_dt(end_dt))

In [108]:
asset_to_view = "DAI"
data = hist_prices.pivot(index = "close_timestamp", columns = 'currency')['close']
data_asset = data.loc[:,asset_to_view]

print(data_asset.dropna())

close_timestamp
2018-12-31T00:00:00Z    1.02811
Name: DAI, dtype: object

In [109]:
# hist_prices[hist_prices['close_timestamp'] == '2018-12-16T00:00:00Z']
hist_prices.groupby('close_timestamp').count()

                      close  currency  open  open_timestamp  volume
close_timestamp
2018-01-16T00:00:00Z      1         1     1               1       1
2018-01-24T00:00:00Z      2         2     2               2       2
2018-02-01T00:00:00Z      1         1     1               1       1
2018-02-10T00:00:00Z      1         1     1               1       1
2018-02-22T00:00:00Z      1         1     1               1       1
2018-02-26T00:00:00Z      1         1     1               1       1
2018-03-03T00:00:00Z      1         1     1               1       1
2018-03-10T00:00:00Z      1         1     1               1       1
2018-03-15T00:00:00Z      1         1     1               1       1
2018-03-23T00:00:00Z      2         2     2               2       2
2018-03-26T00:00:00Z      1         1     1               1       1
2018-03-30T00:00:00Z      3         3     3               3       3
2018-04-06T00:00:00Z      1         1     1               1       1
2018-04-07T00:00:00Z      2         2     2               2       2
2018-04-08T00:00:00Z      1         1     1               1       1
2018-04-11T00:00:00Z      1         1     1               1       1
2018-04-12T00:00:00Z      1         1     1               1       1
2018-04-23T00:00:00Z      1         1     1               1       1
2018-04-27T00:00:00Z      1         1     1               1       1
2018-04-28T00:00:00Z      1         1     1               1       1
2018-05-18T00:00:00Z      2         2     2               2       2
2018-05-25T00:00:00Z      1         1     1               1       1
2018-05-30T00:00:00Z      1         1     1               1       1
2018-05-31T00:00:00Z      2         2     2               2       2
2018-06-01T00:00:00Z      1         1     1               1       1
2018-06-02T00:00:00Z      1         1     1               1       1
2018-06-06T00:00:00Z      1         1     1               1       1
2018-06-09T00:00:00Z      1         1     1               1       1
2018-06-10T00:00:00Z      1         1     1               1       1
2018-06-19T00:00:00Z      2         2     2               2       2
...                     ...       ...   ...             ...     ...
2018-11-30T00:00:00Z      4         4     4               4       4
2018-12-01T00:00:00Z      3         3     3               3       3
2018-12-02T00:00:00Z      2         2     2               2       2
2018-12-03T00:00:00Z      2         2     2               2       2
2018-12-04T00:00:00Z      2         2     2               2       2
2018-12-05T00:00:00Z      3         3     3               3       3
2018-12-06T00:00:00Z      3         3     3               3       3
2018-12-07T00:00:00Z      2         2     2               2       2
2018-12-08T00:00:00Z      2         2     2               2       2
2018-12-09T00:00:00Z      2         2     2               2       2
2018-12-11T00:00:00Z      4         4     4               4       4
2018-12-12T00:00:00Z      1         1     1               1       1
2018-12-14T00:00:00Z      2         2     2               2       2
2018-12-15T00:00:00Z      5         5     5               5       5
2018-12-16T00:00:00Z      3         3     3               3       3
2018-12-17T00:00:00Z      2         2     2               2       2
2018-12-18T00:00:00Z      4         4     4               4       4
2018-12-19T00:00:00Z      4         4     4               4       4
2018-12-20T00:00:00Z      5         5     5               5       5
2018-12-21T00:00:00Z      7         7     7               7       7
2018-12-22T00:00:00Z      6         6     6               6       6
2018-12-23T00:00:00Z      8         8     8               8       8
2018-12-24T00:00:00Z     12        12    12              12      12
2018-12-25T00:00:00Z     11        11    11              11      11
2018-12-26T00:00:00Z     18        18    18              18      18
2018-12-27T00:00:00Z     19        19    19              19      19
2018-12-28T00:00:00Z     29        29    29              29      29
2018-12-29T00:00:00Z     35        35    35              35      35
2018-12-30T00:00:00Z     50        50    50              50      50
2018-12-31T00:00:00Z    778       778   778             778     778

[141 rows x 5 columns]